package uni_system;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class lecturer extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public lecturer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        logo = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        homebu = new javax.swing.JButton();
        addbn = new javax.swing.JButton();
        viewbn = new javax.swing.JButton();
        removebn = new javax.swing.JButton();
        statmu = new javax.swing.JButton();
        card = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        add_lect = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        inserilc = new javax.swing.JButton();
        resetlc = new javax.swing.JButton();
        faculty = new javax.swing.JComboBox<>();
        lecturers_id = new javax.swing.JTextField();
        fullname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        date_of_birth = new javax.swing.JTextField();
        contact_no = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        und_gra = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        post_gra = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        subject = new javax.swing.JTextField();
        subject_id = new javax.swing.JTextField();
        qualification = new javax.swing.JTextField();
        view_lect = new javax.swing.JPanel();
        view_t_index = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        viewbutt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        remove_lect = new javax.swing.JPanel();
        RemoveIndexNo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uni_system/nsbm-team-logo new.jpg"))); // NOI18N

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
        );

        getContentPane().add(logo, java.awt.BorderLayout.PAGE_START);

        menu.setBackground(new java.awt.Color(255, 255, 255));

        homebu.setText("Home");
        homebu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuActionPerformed(evt);
            }
        });

        addbn.setText("Add");
        addbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbnActionPerformed(evt);
            }
        });

        viewbn.setText("View");
        viewbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbnActionPerformed(evt);
            }
        });

        removebn.setText("Remove");
        removebn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removebnActionPerformed(evt);
            }
        });

        statmu.setText("startmenu");
        statmu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statmuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removebn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homebu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(statmu)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statmu)
                .addGap(78, 78, 78)
                .addComponent(homebu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(addbn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(viewbn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(removebn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        card.setLayout(new java.awt.CardLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uni_system/Wani-7-Mar-Lecturers-123RF-700x420.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 696, Short.MAX_VALUE)
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 93, Short.MAX_VALUE))
        );

        card.add(home, "card4");

        add_lect.setBackground(new java.awt.Color(0, 51, 255));

        jLabel9.setText("Qualification");

        inserilc.setText("INSERT");
        inserilc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserilcActionPerformed(evt);
            }
        });

        resetlc.setText("Reset");
        resetlc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetlcActionPerformed(evt);
            }
        });

        faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "School of Computing", "School Of Business", "School Of Engineering" }));
        faculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultyActionPerformed(evt);
            }
        });

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        date_of_birth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_of_birthActionPerformed(evt);
            }
        });

        contact_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_noActionPerformed(evt);
            }
        });

        jLabel1.setText("Faculty");

        jLabel2.setText("Full Name");

        und_gra.setText("under graduate");
        und_gra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                und_graActionPerformed(evt);
            }
        });

        jLabel3.setText("Lectuer Id");

        post_gra.setText("post graduate");
        post_gra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                post_graActionPerformed(evt);
            }
        });

        jLabel4.setText("E-mail");

        jLabel5.setText("Address");

        jLabel6.setText("Contact No");

        jLabel7.setText(" Date Of Birth");

        jLabel8.setText("Gender");

        jLabel10.setText("Subject");

        jLabel11.setText("Subject Id");

        jLabel12.setText("Type");

        buttonGroup1.add(male);
        male.setText("Male");

        buttonGroup1.add(female);
        female.setText("Female");

        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });

        subject_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout add_lectLayout = new javax.swing.GroupLayout(add_lect);
        add_lect.setLayout(add_lectLayout);
        add_lectLayout.setHorizontalGroup(
            add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_lectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_lectLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_lectLayout.createSequentialGroup()
                        .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(add_lectLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(132, 132, 132)
                                .addComponent(qualification))
                            .addGroup(add_lectLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(137, 137, 137)
                                .addComponent(contact_no))
                            .addGroup(add_lectLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(152, 152, 152)
                                .addComponent(address))
                            .addGroup(add_lectLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(163, 163, 163)
                                .addComponent(email))
                            .addGroup(add_lectLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(156, 156, 156)
                                .addComponent(faculty, 0, 275, Short.MAX_VALUE))
                            .addGroup(add_lectLayout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lecturers_id)
                                    .addComponent(fullname)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, add_lectLayout.createSequentialGroup()
                                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(125, 125, 125)
                                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(add_lectLayout.createSequentialGroup()
                                        .addComponent(und_gra)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(post_gra))
                                    .addGroup(add_lectLayout.createSequentialGroup()
                                        .addComponent(male)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(female))
                                    .addComponent(date_of_birth)
                                    .addComponent(subject)
                                    .addComponent(subject_id)))
                            .addGroup(add_lectLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(inserilc)
                                .addGap(63, 63, 63)))
                        .addGap(39, 39, 39)
                        .addComponent(resetlc)
                        .addGap(120, 120, 120))))
        );
        add_lectLayout.setVerticalGroup(
            add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_lectLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lecturers_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(contact_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(date_of_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(male)
                    .addComponent(female))
                .addGap(18, 18, 18)
                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(subject_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(und_gra)
                    .addComponent(post_gra))
                .addGap(18, 18, 18)
                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(qualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserilc)
                    .addComponent(resetlc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        card.add(add_lect, "card2");

        view_lect.setBackground(new java.awt.Color(0, 51, 255));

        jLabel14.setText("INDEX NO");

        viewbutt.setText("view");
        viewbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbuttActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout view_lectLayout = new javax.swing.GroupLayout(view_lect);
        view_lect.setLayout(view_lectLayout);
        view_lectLayout.setHorizontalGroup(
            view_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_lectLayout.createSequentialGroup()
                .addGroup(view_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(view_lectLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel14)
                        .addGap(39, 39, 39)
                        .addComponent(view_t_index, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(viewbutt))
                    .addGroup(view_lectLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
                    .addGroup(view_lectLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        view_lectLayout.setVerticalGroup(
            view_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_lectLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(view_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_t_index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(viewbutt))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        card.add(view_lect, "card3");

        remove_lect.setBackground(new java.awt.Color(0, 51, 255));

        jLabel15.setText("Lectuer Id");

        jButton1.setText("Remove");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout remove_lectLayout = new javax.swing.GroupLayout(remove_lect);
        remove_lect.setLayout(remove_lectLayout);
        remove_lectLayout.setHorizontalGroup(
            remove_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, remove_lectLayout.createSequentialGroup()
                .addContainerGap(377, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(248, 248, 248))
            .addGroup(remove_lectLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(remove_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveIndexNo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        remove_lectLayout.setVerticalGroup(
            remove_lectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(remove_lectLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel15)
                .addGap(46, 46, 46)
                .addComponent(RemoveIndexNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(85, 85, 85))
        );

        card.add(remove_lect, "card5");

        getContentPane().add(card, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void date_of_birthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_of_birthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_of_birthActionPerformed

    private void contact_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact_noActionPerformed

    private void und_graActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_und_graActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_und_graActionPerformed

    private void statmuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statmuActionPerformed
        this.hide();
        home frmlc=new home();
        frmlc.setVisible(true);

    }//GEN-LAST:event_statmuActionPerformed

    private void homebuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuActionPerformed
        home.setVisible(true);
        add_lect.setVisible(false);
        remove_lect.setVisible(false);
        view_lect.setVisible(false);
    }//GEN-LAST:event_homebuActionPerformed

    private void addbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbnActionPerformed
        home.setVisible(false);
        add_lect.setVisible(true);
        remove_lect.setVisible(false);
        view_lect.setVisible(false);
    }//GEN-LAST:event_addbnActionPerformed

    private void viewbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbnActionPerformed
         home.setVisible(false);
        add_lect.setVisible(false);
        remove_lect.setVisible(false);
        view_lect.setVisible(true);
        
        DefaultTableModel tablem_1=(DefaultTableModel)jTable1.getModel();
        tablem_1.setRowCount(0);
       
       try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/form","root","");
            String sql="Select * From lecturers";
            PreparedStatement pst=con.prepareStatement(sql);
            
            ResultSet result_s=pst.executeQuery();
            String col_name1[]={"Full Name","Lecturers Id","Faculty","Email","Address","Contact No","Date Of Birth","Gender","Subject","Subject Id","Type","Qualification"};
            tablem_1.setColumnIdentifiers(col_name1);
            ResultSetMetaData rsmd2=result_s.getMetaData();
            int cols2=rsmd2.getColumnCount();
            while(result_s.next()){
                Object[] obj1=new Object[cols2];
                int i;
                for(i=0;i<cols2;i++){
                    obj1[i]=result_s.getObject(i+1);
                    
                }
                tablem_1.addRow(obj1);
            
         }
       }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);}
                                          

    }//GEN-LAST:event_viewbnActionPerformed

    private void removebnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removebnActionPerformed
        home.setVisible(false);
        add_lect.setVisible(false);
        remove_lect.setVisible(true);
        view_lect.setVisible(false);
    }//GEN-LAST:event_removebnActionPerformed

    private void facultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultyActionPerformed

    private void inserilcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserilcActionPerformed
         try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/form","root","");
            String sql="Insert into lecturers Values (?,?,?,?,?,?,?,?,?,?,?,?) ";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,fullname.getText());
            pst.setString(2,lecturers_id.getText());
            pst.setString(3,faculty.getSelectedItem().toString());
            pst.setString(4,email.getText());
            pst.setString(5,address.getText());
            pst.setString(6,contact_no.getText());
            pst.setString(7,date_of_birth.getText());
             if(male.isSelected()){
                pst.setString(8,"Male");
            }
            else if(female.isSelected()){
                pst.setString(8,"Female");
            }
            pst.setString(9,subject.getText());
            pst.setString(10,subject_id.getText());
             if(und_gra.isSelected()){
                pst.setString(11,"under graduate");
            }
             else if(post_gra.isSelected()){
                pst.setString(11,"post graduate");
            }
              else if(post_gra.isSelected()&& und_gra.isSelected()){
                pst.setString(11,"post graduate,post graduate");
            }
             
            pst.setString(12,qualification.getText());
             
           

            

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"successfully inserted");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_inserilcActionPerformed

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectActionPerformed

    private void post_graActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_post_graActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_post_graActionPerformed

    private void resetlcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetlcActionPerformed
         lecturers_id.setText("");
        fullname.setText("");
        contact_no.setText("");
        email.setText("");
        faculty.setSelectedIndex(0);
        address.setText("");
        date_of_birth.setText("");
        qualification.setText("");
        subject.setText("");
        subject_id.setText("");
        buttonGroup1.clearSelection();
        post_gra.setSelected(false);
        und_gra.setSelected(false);
    }//GEN-LAST:event_resetlcActionPerformed

    private void subject_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject_idActionPerformed

    private void viewbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbuttActionPerformed
        DefaultTableModel tablem_2=(DefaultTableModel)jTable2.getModel();
        tablem_2.setRowCount(0);

        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/form","root","");
            String sql="Select * From lecturers Where Lecturers_Id="+view_t_index.getText()+"";
            PreparedStatement pst=con.prepareStatement(sql);

            ResultSet result_s=pst.executeQuery();
            String col_name2[]={"Full Name","Lecturers Id","Faculty","Email","Address","Contact No","Date Of Birth","Gender","Subject","Subject Id","Type","Qualification"};
            tablem_2.setColumnIdentifiers(col_name2);
            ResultSetMetaData rsmd1=result_s.getMetaData();
            int cols1=rsmd1.getColumnCount();
            while(result_s.next()){
                Object[] obj2=new Object[cols1];
                int i;
                for(i=0;i<cols1;i++){
                    obj2[i]=result_s.getObject(i+1);

                }
                tablem_2.addRow(obj2);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_viewbuttActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               try{
          
    Class.forName("com.mysql.jdbc.Driver");
    Connection con =   DriverManager.getConnection("jdbc:mysql://localhost:3306/form","root","");
    String query="Delete  FROM `lecturers` WHERE Lecturers_Id=?";
    
    PreparedStatement pst=con.prepareStatement(query);
    

    pst.setString(1,RemoveIndexNo.getText());
    pst.executeUpdate();
   
    JOptionPane.showMessageDialog(null, "Removed Detail");
    }
        catch (Exception e) {        
            JOptionPane.showMessageDialog(null, e);
        }
        RemoveIndexNo.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lecturer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RemoveIndexNo;
    private javax.swing.JPanel add_lect;
    private javax.swing.JButton addbn;
    private javax.swing.JTextField address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel card;
    private javax.swing.JTextField contact_no;
    private javax.swing.JTextField date_of_birth;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> faculty;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fullname;
    private javax.swing.JPanel home;
    private javax.swing.JButton homebu;
    private javax.swing.JButton inserilc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField lecturers_id;
    private javax.swing.JPanel logo;
    private javax.swing.JRadioButton male;
    private javax.swing.JPanel menu;
    private javax.swing.JCheckBox post_gra;
    private javax.swing.JTextField qualification;
    private javax.swing.JPanel remove_lect;
    private javax.swing.JButton removebn;
    private javax.swing.JButton resetlc;
    private javax.swing.JButton statmu;
    private javax.swing.JTextField subject;
    private javax.swing.JTextField subject_id;
    private javax.swing.JCheckBox und_gra;
    private javax.swing.JPanel view_lect;
    private javax.swing.JTextField view_t_index;
    private javax.swing.JButton viewbn;
    private javax.swing.JButton viewbutt;
    // End of variables declaration//GEN-END:variables
}
