package uni_system;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class post_std extends javax.swing.JFrame {

    /**
     * Creates new form post_std
     */
    public post_std() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        logop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menup = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        add = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        view = new javax.swing.JButton();
        startmenu = new javax.swing.JButton();
        cardpost = new javax.swing.JPanel();
        homepp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addpp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        faculty = new javax.swing.JTextField();
        male = new javax.swing.JRadioButton();
        contactno = new javax.swing.JTextField();
        female = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        dateofbirth = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        resetbn = new javax.swing.JButton();
        degree = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        qualification = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        indexno = new javax.swing.JTextField();
        insertstu = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        institute = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        year = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        removepp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RemoveIndexNo = new javax.swing.JTextField();
        removepost = new javax.swing.JButton();
        viewpp = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        view_t_index = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        viewbn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logop.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uni_system/nsbm-team-logo new.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout logopLayout = new javax.swing.GroupLayout(logop);
        logop.setLayout(logopLayout);
        logopLayout.setHorizontalGroup(
            logopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logopLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );
        logopLayout.setVerticalGroup(
            logopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(logop, java.awt.BorderLayout.PAGE_START);

        menup.setBackground(new java.awt.Color(255, 255, 255));

        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        remove.setText("REMOVE");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        view.setText("VIEW");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });

        startmenu.setText("Start Menu");
        startmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menupLayout = new javax.swing.GroupLayout(menup);
        menup.setLayout(menupLayout);
        menupLayout.setHorizontalGroup(
            menupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(menupLayout.createSequentialGroup()
                .addComponent(startmenu)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menupLayout.setVerticalGroup(
            menupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menupLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(startmenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        getContentPane().add(menup, java.awt.BorderLayout.LINE_START);

        cardpost.setLayout(new java.awt.CardLayout());

        homepp.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uni_system/Top-15-Fully-Funded-Malaysian-Undergraduate-and-Postgraduate-Scholarships-2018-for-Local-International-Study.jpg"))); // NOI18N
        homepp.add(jLabel3);
        jLabel3.setBounds(0, 0, 630, 420);

        cardpost.add(homepp, "card4");

        addpp.setBackground(new java.awt.Color(0, 51, 255));

        jLabel4.setText("Name");

        jLabel15.setText("Gender");

        buttonGroup1.add(male);
        male.setText("Male");

        buttonGroup1.add(female);
        female.setText("Female");

        jLabel5.setText("Contact no");

        jLabel6.setText("Email");

        resetbn.setText("Reset");
        resetbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbnActionPerformed(evt);
            }
        });

        degree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Master of Computer Science", "Master of Business Administation", "Master in Computer Networks Engineering", " ", " " }));
        degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degreeActionPerformed(evt);
            }
        });

        jLabel7.setText("Degree");

        jLabel8.setText("Faculty");

        jLabel9.setText("Address");

        jLabel10.setText("Date Of Birth");

        jLabel11.setText("Qualification");

        jLabel12.setText("Institute");

        insertstu.setText("Insert");
        insertstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertstuActionPerformed(evt);
            }
        });

        jLabel13.setText("Index No");

        jLabel14.setText("Year");

        address.setColumns(20);
        address.setRows(5);
        jScrollPane2.setViewportView(address);

        javax.swing.GroupLayout addppLayout = new javax.swing.GroupLayout(addpp);
        addpp.setLayout(addppLayout);
        addppLayout.setHorizontalGroup(
            addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addppLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(insertstu)
                .addGap(73, 73, 73)
                .addComponent(resetbn)
                .addGap(158, 158, 158))
            .addGroup(addppLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15)
                    .addGroup(addppLayout.createSequentialGroup()
                        .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(institute, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qualification, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(contactno)
                                .addComponent(email)
                                .addComponent(indexno)
                                .addGroup(addppLayout.createSequentialGroup()
                                    .addComponent(male)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(female)
                                    .addGap(68, 68, 68))
                                .addComponent(faculty)
                                .addComponent(degree, 0, 258, Short.MAX_VALUE)
                                .addComponent(name)
                                .addComponent(jScrollPane2)))))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        addppLayout.setVerticalGroup(
            addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addppLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(indexno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addppLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel7))
                    .addGroup(addppLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(degree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(male))
                    .addComponent(female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addppLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addppLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dateofbirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(qualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(institute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertstu)
                    .addComponent(resetbn))
                .addGap(25, 25, 25))
        );

        cardpost.add(addpp, "card3");

        removepp.setBackground(new java.awt.Color(0, 51, 255));

        jLabel2.setText("INDEX NO");

        removepost.setText("Remove");
        removepost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removepostActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removeppLayout = new javax.swing.GroupLayout(removepp);
        removepp.setLayout(removeppLayout);
        removeppLayout.setHorizontalGroup(
            removeppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeppLayout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(removeppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(RemoveIndexNo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(332, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, removeppLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removepost)
                .addGap(56, 56, 56))
        );
        removeppLayout.setVerticalGroup(
            removeppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeppLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(RemoveIndexNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(removepost)
                .addGap(33, 33, 33))
        );

        cardpost.add(removepp, "card2");

        viewpp.setBackground(new java.awt.Color(0, 51, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jLabel16.setText("INDEX NO");

        viewbn.setText("view");
        viewbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewppLayout = new javax.swing.GroupLayout(viewpp);
        viewpp.setLayout(viewppLayout);
        viewppLayout.setHorizontalGroup(
            viewppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewppLayout.createSequentialGroup()
                .addGroup(viewppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(viewppLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel16)
                        .addGap(39, 39, 39)
                        .addComponent(view_t_index, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(viewbn))
                    .addGroup(viewppLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE))
                    .addGroup(viewppLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewppLayout.setVerticalGroup(
            viewppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewppLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(viewppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(view_t_index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(viewbn))
                .addGap(58, 58, 58)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        cardpost.add(viewpp, "card5");

        getContentPane().add(cardpost, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        homepp.setVisible(true);
        addpp.setVisible(false);
        removepp.setVisible(false);
        viewpp.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        homepp.setVisible(false);
        addpp.setVisible(true);
        removepp.setVisible(false);
        viewpp.setVisible(false);
    }//GEN-LAST:event_addActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        homepp.setVisible(false);
        addpp.setVisible(false);
        removepp.setVisible(true);
        viewpp.setVisible(false);
    }//GEN-LAST:event_removeActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        homepp.setVisible(false);
        addpp.setVisible(false);
        removepp.setVisible(false);
        viewpp.setVisible(true);
        
            DefaultTableModel tablem_1=(DefaultTableModel)jTable1.getModel();
         tablem_1.setRowCount(0);
       
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/form","root","");
            String sql="Select * From post_stu_detail";
            PreparedStatement pst=con.prepareStatement(sql);
            
            ResultSet result_s=pst.executeQuery();
            String col_name1[]={"Index No","Name","Contact No","Email","Degree","Gender","Faculty","Address","Date Of Birth","Qualification","Institute","Year"};
            tablem_1.setColumnIdentifiers(col_name1);
            ResultSetMetaData rsmd2=result_s.getMetaData();
            int cols2=rsmd2.getColumnCount();
            while(result_s.next()){
                Object[] obj1=new Object[cols2];
                int i;
                for(i=0;i<cols2;i++){
                    obj1[i]=result_s.getObject(i+1);
                    
                }
                tablem_1.addRow(obj1);
            
            }
        } 
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_viewActionPerformed

    private void resetbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbnActionPerformed
        indexno.setText("");
        name.setText("");
        contactno.setText("");
        email.setText("");
        degree.setSelectedIndex(0);
        faculty.setText("");
        address.setText("");
        dateofbirth.setText("");
        qualification.setText("");
        institute.setText("");
        year.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_resetbnActionPerformed

    private void degreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degreeActionPerformed
        if(degree.getSelectedItem().toString().equals("Master of Computer Science") ){
            faculty.setText("School of Computing");
        }

       
        else if(degree.getSelectedItem().toString().equals(
"Master of Business Administation" )){
            faculty.setText("School Of Business");
        }

       
        else if(degree.getSelectedItem().toString().equals(
"Master in Computer Networks Engineering" )){
            faculty.setText("School Of Engineering");
        }

    }//GEN-LAST:event_degreeActionPerformed

    private void insertstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertstuActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/form","root","");
            String sql="Insert into post_stu_detail Values (?,?,?,?,?,?,?,?,?,?,?,?) ";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,indexno.getText());
            pst.setString(2,name.getText());
            pst.setString(3,contactno.getText());
            pst.setString(4,email.getText());
            pst.setString(5,degree.getSelectedItem().toString());
             if(male.isSelected()){
                pst.setString(6,"male");
            }
            else if(female.isSelected()){
                pst.setString(6,"female");
            }
            pst.setString(7,faculty.getText());
            pst.setString(8,address.getText());
            pst.setString(9,dateofbirth.getText());
            pst.setString(10,qualification.getText());
            pst.setString(11,institute.getText());
            pst.setString(12,year.getText());
            

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"successfully inserted");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_insertstuActionPerformed

    private void viewbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbnActionPerformed
        DefaultTableModel tablem_2=(DefaultTableModel)jTable2.getModel();
        tablem_2.setRowCount(0);

        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/form","root","");
            String sql="Select * From post_stu_detail Where Index_No="+view_t_index.getText()+"";
            PreparedStatement pst=con.prepareStatement(sql);

            ResultSet result_s=pst.executeQuery();
            String col_name2[]={"Index No","Name","Contact No","Email","Degree","Gender","Faculty","Address","Date Of Birth","Qualification","Institute","Year"};
            tablem_2.setColumnIdentifiers(col_name2);
            ResultSetMetaData rsmd1=result_s.getMetaData();
            int cols1=rsmd1.getColumnCount();
            while(result_s.next()){
                Object[] obj2=new Object[cols1];
                int i;
                for(i=0;i<cols1;i++){
                    obj2[i]=result_s.getObject(i+1);

                }
                tablem_2.addRow(obj2);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_viewbnActionPerformed

    private void startmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startmenuActionPerformed
       this.hide();
       home frmp=new home();
       frmp.setVisible(true);
    }//GEN-LAST:event_startmenuActionPerformed

    private void removepostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removepostActionPerformed
        // TODO add your handling code here:
          try{
          
    Class.forName("com.mysql.jdbc.Driver");
    Connection con =   DriverManager.getConnection("jdbc:mysql://localhost:3306/form","root","");
    String query="Delete  FROM `post_stu_detail` WHERE Index_No=?";
    
    PreparedStatement pst=con.prepareStatement(query);
    

    pst.setString(1,RemoveIndexNo.getText());
    pst.executeUpdate();
   
    JOptionPane.showMessageDialog(null, "Removed Detail");
    }
        catch (Exception e) {        
            JOptionPane.showMessageDialog(null, e);
        }
        RemoveIndexNo.setText("");
        
    }//GEN-LAST:event_removepostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(post_std.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(post_std.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(post_std.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(post_std.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new post_std().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RemoveIndexNo;
    private javax.swing.JButton add;
    private javax.swing.JPanel addpp;
    private javax.swing.JTextArea address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cardpost;
    private javax.swing.JTextField contactno;
    private javax.swing.JTextField dateofbirth;
    private javax.swing.JComboBox<String> degree;
    private javax.swing.JTextField email;
    private javax.swing.JTextField faculty;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton home;
    private javax.swing.JPanel homepp;
    private javax.swing.JTextField indexno;
    private javax.swing.JButton insertstu;
    private javax.swing.JTextField institute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel logop;
    private javax.swing.JRadioButton male;
    private javax.swing.JPanel menup;
    private javax.swing.JTextField name;
    private javax.swing.JTextField qualification;
    private javax.swing.JButton remove;
    private javax.swing.JButton removepost;
    private javax.swing.JPanel removepp;
    private javax.swing.JButton resetbn;
    private javax.swing.JButton startmenu;
    private javax.swing.JButton view;
    private javax.swing.JTextField view_t_index;
    private javax.swing.JButton viewbn;
    private javax.swing.JPanel viewpp;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
